[phases.setup]
nixPkgs = ["python311", "nodejs"]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python -m playwright install chromium"
]

[start]
cmd = "python railway_start.py" 