[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
    "python -m pip install -r requirements.txt",
    "python -m playwright install chromium"
]

[start]
cmd = "python railway_start.py" 