[build]
builder = "nixpacks"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/api/status"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 15

[env]
PORT = "8080"
NODE_VERSION = "18"
