[build]
builder = "dockerfile"

[deploy]
startCommand = "python -m uvicorn app:app --host 0.0.0.0 --port 8000 --log-level info"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 20

[env]
PYTHON_VERSION = "3.11"
PORT = "8000"
