[build]
builder = "nixpacks"

[deploy]
startCommand = "python railway_start.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
RAILWAY_DEPLOY = "True"
PORT = "8000"
