[build]
builder = "dockerfile"

[deploy]
startCommand = "python railway_startup.py"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 20

[env]
PYTHON_VERSION = "3.11"
PORT = "8000"
