[build]
builder = "nixpacks"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8080"
NODE_VERSION = "18"
