[build]
  builder = "nixpacks"

[deploy]
  startCommand = "python railway_start.py"
  restartPolicyType = "on-failure"
  restartPolicyMaxRetries = 3

[build.environment]
  PYTHON_VERSION = "3.11"
  NIXPACKS_PYTHON_VERSION = "3.11"