[build]
builder = "nixpacks"

[deploy]
startCommand = "python railway_start.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8080"
