[build]
builder = "dockerfile"

[deploy]
startCommand = "python railway_start.py"
healthcheckPath = "/api/status"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PYTHON_VERSION = "3.11"
PORT = "8000"
