[build]
builder = "dockerfile"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 15

[env]
PYTHON_VERSION = "3.11"
PORT = "8000"
