[build]
builder = "nixpacks"

[deploy]
startCommand = "python railway_start.py"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[env]
PORT = "8080"
RAILWAY_DEPLOY = "True"
