# Middlewares dinâmicos do Traefik
http:
  middlewares:
    # Rate limiting
    rate-limit:
      rateLimit:
        average: 100
        burst: 50
        period: 1m
    
    # Headers de segurança
    security-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          server: ""
          X-Powered-By: ""
    
    # Compressão
    gzip:
      compress:
        excludedContentTypes:
          - text/event-stream
    
    # CORS para API
    cors:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - DELETE
          - PATCH
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginList:
          - "http://localhost"
          - "https://localhost"
          - "http://claudia.localhost"
          - "https://claudia.localhost"
        accessControlMaxAge: 100
        addVaryHeader: true
        accessControlAllowCredentials: true
    
    # WebSocket específico
    websocket:
      headers:
        customRequestHeaders:
          Connection: "Upgrade"
          Upgrade: "websocket"
    
    # Retry em caso de falha
    retry:
      retry:
        attempts: 3
        initialInterval: 100ms
        
    # Circuit breaker
    circuit-breaker:
      circuitBreaker:
        expression: "NetworkErrorRatio() > 0.5"
        
    # Buffering para uploads grandes
    buffering:
      buffering:
        maxRequestBodyBytes: 10485760  # 10MB
        memRequestBodyBytes: 2097152   # 2MB
        maxResponseBodyBytes: 10485760 # 10MB
        memResponseBodyBytes: 2097152  # 2MB
        retryExpression: "IsNetworkError() && Attempts() < 2"